# Generated by Django 3.0.2 on 2020-01-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassinfo',
            name='class_short_name',
            field=models.CharField(max_length=10),
        ),
    ]
