# Generated by Django 3.0.2 on 2020-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200118_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailsinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
