# Generated by Django 3.0.2 on 2020-02-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200215_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailsinfo',
            name='std_class',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='std_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClassInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetailsinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
    ]
