# Generated by Django 3.0.2 on 2020-02-16 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200216_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='std_class',
        ),
        migrations.AddField(
            model_name='studentdetailsinfo',
            name='std_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClassInfo'),
            preserve_default=False,
        ),
    ]
